import React, { useCallback, useEffect, useState } from 'react';
import { BACKEND_URL as B } from '../config';

const css = `
.ad{min-height:100vh;background:#f3f4f6;padding:16px;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif;color:#111827}
.ac{max-width:1180px;margin:0 auto 14px;background:#fff;border-radius:18px;padding:16px;box-shadow:0 4px 18px rgba(0,0,0,.08)}
.header,.section-head,.toolbar{display:flex;align-items:center;gap:10px}.header,.section-head{justify-content:space-between}.brand h1{margin:0;font-size:24px}.muted{color:#6b7280;font-size:13px;line-height:1.45}.status-dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#16a34a;margin-right:6px}
.cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}
.metric{position:relative;padding:14px;border:1px solid #eceff1;border-radius:15px;background:linear-gradient(180deg,#fff 0%,#f7f8f9 100%);min-height:84px;overflow:hidden}.metric::after{content:'';position:absolute;right:-18px;top:-18px;width:54px;height:54px;border-radius:50%;background:#eef0f2}.metric b{display:block;position:relative;z-index:1;font-size:12px;color:#6b7280;line-height:1.2;padding-right:18px}.metric strong{display:block;position:relative;z-index:1;font-size:28px;line-height:1;margin-top:9px;letter-spacing:-.03em}.metric small{display:block;position:relative;z-index:1;margin-top:5px;color:#6b7280;font-size:10px;line-height:1.2}
.summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-top:12px}.mini{padding:12px;border-radius:12px;background:#f5f6f7}.mini b{display:block;font-size:11px;color:#6b7280}.mini strong{display:block;font-size:20px;margin-top:4px}
.table-wrap{overflow:auto}.table{width:100%;min-width:760px;border-collapse:collapse}.table th,.table td{padding:11px 9px;border-bottom:1px solid #eee;text-align:left;font-size:13px}.table th{font-size:11px;color:#6b7280;text-transform:uppercase}.btn{border:0;border-radius:11px;padding:10px 13px;font-weight:800;cursor:pointer}.btn:disabled{opacity:.55}.dark{background:#111827;color:#fff}.yes{background:#16a34a;color:#fff}.no{background:#dc2626;color:#fff}.secondary{background:#eef0f2;color:#111827}.toolbar{flex-wrap:wrap;margin-top:12px}.badge{display:inline-flex;border-radius:999px;padding:5px 9px;font-size:11px;font-weight:800}.badge.pending{background:#fff7ed;color:#c2410c}.badge.approved{background:#ecfdf5;color:#15803d}.badge.rejected{background:#fef2f2;color:#b91c1c}.ok{background:#ecfdf5;color:#15803d;padding:10px 12px;border-radius:10px}.error{background:#fff1f2;color:#9f1239;padding:10px 12px;border-radius:10px}.refresh{font-size:12px;color:#6b7280;margin-top:7px}
.chart{display:flex;align-items:flex-end;gap:8px;height:160px}.chart-item{flex:1;min-width:22px}.bar-wrap{height:160px;display:flex;align-items:flex-end}.bar{width:100%;background:#111;border-radius:7px 7px 0 0;min-height:8px}.bar-label{text-align:center;font-size:10px;color:#6b7280;margin-top:5px;white-space:nowrap;overflow:hidden}.modal-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.5);z-index:5000;display:flex;align-items:center;justify-content:center;padding:12px}.modal{width:min(100%,420px);background:#fff;border-radius:18px;padding:20px;box-shadow:0 30px 80px rgba(0,0,0,.3)}.modal h2{margin:0 0 8px}.modal label{display:block;font-size:13px;font-weight:800;margin:12px 0 6px}.field{width:100%;min-height:48px;box-sizing:border-box;border:1px solid #d1d5db;border-radius:12px;padding:12px;font-size:16px}.password-wrap{position:relative}.password-wrap .field{padding-right:84px}.password-toggle{position:absolute;right:7px;top:50%;transform:translateY(-50%);border:0;border-radius:8px;background:#eef0f2;padding:7px 9px;font-weight:800;color:#111827}.modal-actions{display:flex;gap:8px;margin-top:14px}.modal-actions>*{flex:1}
@media(max-width:900px){.cards{grid-template-columns:repeat(2,minmax(0,1fr))}.summary{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:520px){.ad{padding:8px}.ac{padding:12px;border-radius:16px}.cards{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.metric{min-height:96px;padding:12px 11px;border-radius:13px}.metric strong{font-size:24px;margin-top:8px}.metric b{font-size:11px;min-height:27px}.metric small{font-size:9px}.summary{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.mini{padding:10px}.mini strong{font-size:18px}.header,.section-head{align-items:flex-start;flex-direction:row}.brand h1{font-size:19px}.toolbar{display:grid;grid-template-columns:1fr 1fr;gap:7px}.toolbar .btn{width:100%;padding:10px 8px;font-size:12px}.table{min-width:760px}.modal{padding:16px}.modal-actions{flex-direction:column}}
@media(max-width:360px){.metric{min-height:90px;padding:10px 9px}.metric strong{font-size:22px}.metric b{font-size:10px}.metric small{display:none}.ac{padding:10px}.toolbar{grid-template-columns:1fr}.brand h1{font-size:18px}}
`;

async function readJson(response){const text=await response.text();if(!text)return {};try{return JSON.parse(text)}catch{return {}}}
function statusLabel(status){return status==='approved'?'Aprovado':status==='rejected'?'Rejeitado':'Pendente'}

export default function AdminDashboardPro({admin,onLogout}){
 const [data,setData]=useState(null);const [apps,setApps]=useState([]);const [loading,setLoading]=useState(true);const [msg,setMsg]=useState('');const [lastUpdate,setLastUpdate]=useState(null);const [reviewing,setReviewing]=useState(null);const [passwordOpen,setPasswordOpen]=useState(false);const [newPassword,setNewPassword]=useState('');const [showPassword,setShowPassword]=useState(false);const [passwordBusy,setPasswordBusy]=useState(false);
 const load=useCallback(async(silent=false)=>{const token=localStorage.getItem('adminToken');if(!token){onLogout();return}if(!silent)setLoading(true);const headers={Authorization:`Bearer ${token}`};let anyError=false;
  const loadApps=async()=>{try{const r=await fetch(`${B}/api/drivers/applications`,{headers,cache:'no-store'});const j=await readJson(r);if(r.status===401){onLogout();return}if(!r.ok)throw new Error(j.error||'Erro ao listar cadastros de motoristas.');setApps(Array.isArray(j.applications)?j.applications:[])}catch(e){anyError=true;setMsg(e.message||'Erro ao listar cadastros de motoristas.')}};
  const loadStats=async()=>{try{const r=await fetch(`${B}/api/admin-stats/overview`,{headers,cache:'no-store'});const j=await readJson(r);if(r.status===401){onLogout();return}if(!r.ok)throw new Error(j.error||'Erro ao carregar estatísticas.');setData(j)}catch(e){anyError=true;setMsg(prev=>prev||e.message||'Erro ao carregar estatísticas.')}};
  await Promise.all([loadApps(),loadStats()]);setLastUpdate(new Date());setLoading(false);if(!anyError)setMsg('');
 },[onLogout]);
 useEffect(()=>{load();const id=setInterval(()=>load(true),5000);return()=>clearInterval(id)},[load]);
 const review=async(uid,status)=>{if(reviewing)return;const token=localStorage.getItem('adminToken');if(!token){onLogout();return}setReviewing(`${uid}:${status}`);setMsg('');try{const r=await fetch(`${B}/api/drivers/${uid}/approval`,{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({status})});const j=await readJson(r);if(r.status===401){onLogout();return}if(!r.ok)throw new Error(j.error||'Erro ao atualizar motorista.');setMsg(status==='approved'?'Motorista aprovado com sucesso.':'Motorista rejeitado.');await load(true)}catch(e){setMsg(e.message||'Não foi possível atualizar o motorista.')}finally{setReviewing(null)}};
 const setAdminPassword=async(e)=>{e.preventDefault();const token=localStorage.getItem('adminToken');if(!token){onLogout();return}if(newPassword.length<8){setMsg('A nova senha deve ter pelo menos 8 caracteres.');return}setPasswordBusy(true);setMsg('');try{const r=await fetch(`${B}/api/auth/admin/set-password`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({newPassword})});const j=await readJson(r);if(r.status===401){onLogout();return}if(!r.ok)throw new Error(j.error||'Não foi possível alterar a senha.');setPasswordOpen(false);setNewPassword('');setShowPassword(false);setMsg('Senha administrativa alterada com sucesso.')}catch(e){setMsg(e.message||'Não foi possível alterar a senha.')}finally{setPasswordBusy(false)}};
 const t=data?.totals||{};const num=v=>loading&&!data?'…':Number.isFinite(Number(v))?Number(v):0;const pending=apps.filter(x=>x.status==='pending').length;const approved=apps.filter(x=>x.status==='approved').length;const rejected=apps.filter(x=>x.status==='rejected').length;
 return <div className="ad"><style>{css}</style>
  <div className="ac"><div className="header"><div className="brand"><h1>🔐 Painel administrativo</h1><div className="muted"><span className="status-dot"/>{admin?.name||admin?.email||'Administrador'} • dados em tempo real</div></div><button className="btn no" onClick={onLogout}>Sair</button></div>{msg&&<p className={msg.includes('sucesso')?'ok':'error'}>{msg}</p>}<div className="refresh">{lastUpdate?`Última atualização: ${lastUpdate.toLocaleTimeString('pt-BR')}`:loading?'Carregando dados…':'Aguardando atualização'}</div><div className="toolbar"><button className="btn dark" onClick={()=>setPasswordOpen(true)}>🔑 Alterar senha</button><button className="btn secondary" onClick={()=>load(false)}>↻ Atualizar agora</button></div></div>
  <div className="ac"><div className="cards"><div className="metric"><b>Passageiros</b><strong>{num(t.passengers)}</strong><small>contas cadastradas</small></div><div className="metric"><b>Motoristas cadastrados</b><strong>{num(t.drivers)}</strong><small>cadastros únicos</small></div><div className="metric"><b>Motoristas online</b><strong>{num(t.onlineDrivers)}</strong><small>aprovados e online</small></div><div className="metric"><b>Motoristas aprovados</b><strong>{num(t.approvedDrivers)}</strong><small>liberados para trabalhar</small></div><div className="metric"><b>Cadastros pendentes</b><strong>{num(t.pendingDrivers)}</strong><small>aguardando análise</small></div><div className="metric"><b>Corridas hoje</b><strong>{num(t.ridesToday)}</strong><small>solicitações do dia</small></div><div className="metric"><b>Corridas ativas</b><strong>{num(t.activeRides)}</strong><small>em andamento</small></div><div className="metric"><b>Receita hoje</b><strong>R$ {Number(t.revenueToday||0).toFixed(2)}</strong><small>corridas concluídas</small></div></div></div>
  <div className="ac"><div className="section-head"><h2>🚗 Resumo dos motoristas</h2><span className="muted">Mesma base da lista</span></div><div className="summary"><div className="mini"><b>Total</b><strong>{apps.length}</strong></div><div className="mini"><b>Pendentes</b><strong>{pending}</strong></div><div className="mini"><b>Aprovados</b><strong>{approved}</strong></div><div className="mini"><b>Rejeitados</b><strong>{rejected}</strong></div></div></div>
  {data?.daily&&<div className="ac"><h2>📈 Últimos 7 dias</h2><div className="chart">{data.daily.map(d=><div key={d.date} style={{flex:1,minWidth:20,textAlign:'center'}}><div style={{height:135,display:'flex',alignItems:'flex-end'}}><div className="bar" style={{height:`${Math.max(8,Math.min(135,Number(d.rides||0)*14))}px`}}/></div><div className="bar-label">{new Date(`${d.date}T12:00:00`).toLocaleDateString('pt-BR',{weekday:'short'}).replace('.','')}</div></div>)}</div></div>
  <div className="ac"><div className="section-head"><div><h2>📋 Cadastros de motoristas</h2><div className="muted">Sincronizados automaticamente com o Firebase.</div></div></div>{apps.length===0?<p className="muted">{loading?'Carregando cadastros…':'Nenhum cadastro encontrado.'}</p>:<div className="table-wrap"><table className="table"><thead><tr><th>Motorista</th><th>Contato</th><th>Veículo</th><th>Status</th><th>Ação</th></tr></thead><tbody>{apps.map(a=><tr key={a.uid}><td><b>{a.fullName||'Sem nome'}</b></td><td>{a.email||'—'}<br/>{a.phone||'—'}</td><td>{a.vehicleModel||'—'}<br/>{a.licensePlate||'—'}</td><td><span className={`badge ${a.status}`}>{statusLabel(a.status)}</span></td><td>{a.status==='pending'?<><button className="btn yes" disabled={!!reviewing} onClick={()=>review(a.uid,'approved')}>{reviewing===`${a.uid}:approved`?'Aprovando…':'Aprovar'}</button>{' '}<button className="btn no" disabled={!!reviewing} onClick={()=>review(a.uid,'rejected')}>{reviewing===`${a.uid}:rejected`?'Rejeitando…':'Rejeitar'}</button></>:<span className="muted">Revisado</span>}</td></tr>)}</tbody></table></div>}</div>
  {passwordOpen&&<div className="modal-backdrop" onClick={()=>!passwordBusy&&setPasswordOpen(false)}><div className="modal" onClick={e=>e.stopPropagation()}><h2>🔑 Nova senha administrativa</h2><p className="muted">Crie uma nova senha sem informar a anterior.</p><form onSubmit={setAdminPassword}><label htmlFor="admin-new-password">Nova senha</label><div className="password-wrap"><input id="admin-new-password" className="field" type={showPassword?'text':'password'} value={newPassword} onChange={e=>setNewPassword(e.target.value)} minLength={8} autoComplete="new-password" placeholder="Mínimo de 8 caracteres" required/><button type="button" className="password-toggle" onClick={()=>setShowPassword(v=>!v)}>{showPassword?'Ocultar':'Mostrar'}</button></div><div className="modal-actions"><button type="button" className="btn secondary" disabled={passwordBusy} onClick={()=>setPasswordOpen(false)}>Cancelar</button><button type="submit" className="btn dark" disabled={passwordBusy}>{passwordBusy?'Salvando…':'Salvar senha'}</button></div></form></div></div>}
 </div>
}
