import React, { useEffect, useMemo, useRef, useState } from 'react';
import axios from 'axios';
import { BACKEND_URL } from '../config';
import WebSocketService from '../services/WebSocketService';
import DriverRideMap from '../components/DriverRideMap';

const ACTIVE = ['ACCEPTED', 'IN_PROGRESS'];
const ARRIVAL_RADIUS_KM = 0.15;
const norm = v => { if (!v) return null; const s = v.location || v.currentLocation || v; const lat = Number(s.lat ?? s.latitude), lng = Number(s.lng ?? s.longitude); return Number.isFinite(lat) && Number.isFinite(lng) ? { lat, lng } : null; };
const dist = (a,b) => { const p=norm(a), q=norm(b); if(!p||!q) return Infinity; const R=6371,d1=(q.lat-p.lat)*Math.PI/180,d2=(q.lng-p.lng)*Math.PI/180,x=Math.sin(d1/2)**2+Math.cos(p.lat*Math.PI/180)*Math.cos(q.lat*Math.PI/180)*Math.sin(d2/2)**2; return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x)); };
const passengerAt = r => norm(r && (r.passengerLocation || r.origin?.location));
const destinationAt = r => norm(r && r.destination?.location);
const errText = (e,f) => e?.response?.data?.error || e?.response?.data?.details || e?.message || f;
function Avatar({photo,name}){return <div className="driver-avatar">{photo?<img src={photo} alt={name||'Passageiro'}/>:String(name||'P').trim().charAt(0).toUpperCase()}</div>}

export default function DriverDashboardV2(){
 const [user]=useState(()=>{try{return JSON.parse(localStorage.getItem('user')||'null')}catch(_){return null}});
 const [online,setOnline]=useState(false),[requests,setRequests]=useState([]),[ride,setRide]=useState(null),[driverLocation,setDriverLocation]=useState(null),[passengerLocation,setPassengerLocation]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[completed,setCompleted]=useState(null);
 const rideRef=useRef(null), onlineRef=useRef(false), watchRef=useRef(null), completeTimer=useRef(null);
 const token=localStorage.getItem('token'),uid=user?.uid,headers=useMemo(()=>({Authorization:'Bearer '+token}),[token]);
 useEffect(()=>{rideRef.current=ride},[ride]); useEffect(()=>{onlineRef.current=online},[online]);
 const stopGPS=()=>{if(watchRef.current!==null&&navigator.geolocation)navigator.geolocation.clearWatch(watchRef.current);watchRef.current=null};
 const startGPS=()=>{if(!navigator.geolocation||watchRef.current!==null)return;watchRef.current=navigator.geolocation.watchPosition(p=>{const l={lat:Number(p.coords.latitude),lng:Number(p.coords.longitude)};if(!Number.isFinite(l.lat)||!Number.isFinite(l.lng))return;setDriverLocation(l);if(rideRef.current?.id)WebSocketService.sendLocation(rideRef.current.id,uid,l.lat,l.lng);else if(onlineRef.current)WebSocketService.sendPresenceLocation(l.lat,l.lng)},()=>{},{enableHighAccuracy:true,maximumAge:2500,timeout:10000})};
 const clearRide=msg=>{setRide(null);setPassengerLocation(null);stopGPS();if(onlineRef.current)startGPS();if(msg)setMessage(msg)};
 async function active(){try{const r=await axios.get(BACKEND_URL+'/api/rides/active',{headers,timeout:8000});const a=r.data?.ride;if(a?.id&&String(a.driverId)===String(uid)&&ACTIVE.includes(a.status)){setRide(a);setPassengerLocation(passengerAt(a));startGPS();WebSocketService.connect();WebSocketService.joinRideRoom(a.id);return a}}catch(_){}return null}
 useEffect(()=>{if(!token||!uid)return;const s=WebSocketService.connect();
  const join=async()=>{if(onlineRef.current)WebSocketService.joinDriversRoom();if(rideRef.current?.id){WebSocketService.joinRideRoom(rideRef.current.id);await active()}};
  const onReq=d=>{const x={...(d||{}),id:d&&(d.id||d.rideId)};if(!x.id||rideRef.current)return;setRequests(a=>a.some(i=>String(i.id)===String(x.id))?a:[x,...a])};
  const onUn=d=>{const id=d&&(d.id||d.rideId);if(id)setRequests(a=>a.filter(i=>String(i.id)!==String(id)))};
  const onAcc=d=>{const x=d&&(d.ride||d);if(!x?.id)return;if(String(x.driverId)===String(uid)){setRide(x);setPassengerLocation(passengerAt(x));setRequests(a=>a.filter(i=>String(i.id)!==String(x.id)));startGPS();WebSocketService.joinRideRoom(x.id);setMessage('Corrida aceita. Mapa e rota até o passageiro abertos.')}else if(x.driverId)setRequests(a=>a.filter(i=>String(i.id)!==String(x.id)))};
  const onPL=d=>{if(!d?.rideId||!rideRef.current||String(d.rideId)!==String(rideRef.current.id))return;const l=norm(d.location);if(!l)return;setPassengerLocation(l);setRide(r=>r?{...r,passengerLocation:l,origin:{...(r.origin||{}),location:l}:r)};
  const onStart=d=>{const x=d&&(d.ride||d);if(x?.id&&String(x.id)===String(rideRef.current?.id)){setRide(r=>r?{...r,...x,status:'IN_PROGRESS'}:r);setMessage('Passageiro embarcou. Rota até o destino ativa.')}};
  const finish=x=>{setCompleted({price:Number(x?.price??rideRef.current?.price??0),distance:Number(x?.distance??rideRef.current?.distance??0),passengerName:x?.passengerName||rideRef.current?.passengerName||'Passageiro'});clearRide('Corrida finalizada com sucesso.');if(completeTimer.current)clearTimeout(completeTimer.current);completeTimer.current=setTimeout(()=>{setCompleted(null);setMessage('Pronto para receber a próxima corrida.');if(onlineRef.current)startGPS()},4000)};
  const onEnd=d=>{const x=d&&(d.ride||d);if(x?.id&&String(x.id)===String(rideRef.current?.id))finish(x)};
  const onCancel=d=>{const id=d&&(d.rideId||d.ride?.id);if(id&&rideRef.current&&String(id)===String(rideRef.current.id))clearRide('O passageiro cancelou a corrida. Você voltou ao painel inicial.')};
  s?.on('connect',join);WebSocketService.onNewRideRequest(onReq);WebSocketService.onRideUnavailable(onUn);WebSocketService.onRideAccepted(onAcc);WebSocketService.onPassengerLocationUpdate(onPL);WebSocketService.onRideStarted(onStart);WebSocketService.onRideEnded(onEnd);WebSocketService.onRideCancelled(onCancel);
  return()=>{s?.off('connect',join);WebSocketService.off('new-ride-request',onReq);WebSocketService.off('ride-unavailable',onUn);WebSocketService.off('ride-accepted',onAcc);WebSocketService.off('passenger-location-update',onPL);WebSocketService.off('ride-started',onStart);WebSocketService.off('ride-ended',onEnd);WebSocketService.off('ride-cancelled',onCancel);if(completeTimer.current)clearTimeout(completeTimer.current);stopGPS();WebSocketService.disconnect()}
 },[token,uid,headers]);
 useEffect(()=>{if(!token||!uid)return;let dead=false;Promise.all([axios.get(BACKEND_URL+'/api/drivers/me',{headers}),axios.get(BACKEND_URL+'/api/rides/history?limit=20',{headers})]).then(([a,b])=>{if(dead)return;const d=a.data?.driver,o=d?.status==='approved'&&d?.isOnline===true;onlineRef.current=o;setOnline(o);const r=(b.data?.rides||[]).find(x=>ACTIVE.includes(x.status)&&String(x.driverId)===String(uid));if(r){setRide(r);setPassengerLocation(passengerAt(r));startGPS();WebSocketService.connect();WebSocketService.joinRideRoom(r.id)}if(o){WebSocketService.connect();WebSocketService.joinDriversRoom();startGPS()}}).catch(()=>{});return()=>{dead=true}},[token,uid,headers]);
 useEffect(()=>{if(!token||!uid||!online)return;let dead=false;const sync=async()=>{if(dead||!onlineRef.current||rideRef.current)return;try{const r=await axios.get(BACKEND_URL+'/api/rides/pending',{headers,timeout:8000});const p=r.data?.rides||[];if(!dead&&!rideRef.current)setRequests(a=>p.filter(x=>x?.id).concat(a).filter((x,i,all)=>x&&all.findIndex(y=>String(y.id)===String(x.id))===i).slice(0,20))}catch(_){}};sync();const t=setInterval(sync,3500);return()=>{dead=true;clearInterval(t)}},[token,uid,online,headers]);
 useEffect(()=>{if(!token||!uid||!ride)return;let dead=false;const sync=async()=>{if(dead||!rideRef.current)return;try{const r=await axios.get(BACKEND_URL+'/api/rides/active',{headers,timeout:8000});const a=r.data?.ride;if(!a||String(a.id)!==String(rideRef.current.id)){clearRide('A corrida foi encerrada/cancelada. Você voltou ao painel inicial.');return}setRide(x=>x?{...x,...a}:a);const p=passengerAt(a);if(p)setPassengerLocation(p)}catch(_){}};sync();const t=setInterval(sync,3000);return()=>{dead=true;clearInterval(t)}},[token,uid,ride?.id,headers]);
 async function toggle(){if(busy||!uid||rideRef.current)return;setBusy(true);try{if(!onlineRef.current){if(!navigator.geolocation)throw Error('Localização não disponível.');const p=await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,{enableHighAccuracy:true,timeout:12000}));const l={lat:p.coords.latitude,lng:p.coords.longitude};await axios.post(BACKEND_URL+'/api/drivers/'+uid+'/status',{isOnline:true,currentLocation:l},{headers});setDriverLocation(l);WebSocketService.connect();WebSocketService.joinDriversRoom();onlineRef.current=true;setOnline(true);startGPS();setMessage('Você está online e receberá corridas próximas.')}else{stopGPS();await axios.post(BACKEND_URL+'/api/drivers/'+uid+'/status',{isOnline:false},{headers});onlineRef.current=false;setOnline(false);WebSocketService.disconnect();setRequests([]);setMessage('Você ficou offline.')}}catch(e){setMessage(errText(e,'Não foi possível alterar o status.'))}finally{setBusy(false)}}
 async function accept(r){if(busy||rideRef.current||!r?.id)return;setBusy(true);setMessage('Aceitando corrida…');try{const a=(await axios.post(BACKEND_URL+'/api/rides/accept',{rideId:r.id},{headers,timeout:15000})).data?.ride;if(!a?.id)throw Error('O servidor não retornou os dados da corrida.');setRide(a);setPassengerLocation(passengerAt(a));setRequests(x=>x.filter(i=>String(i.id)!==String(r.id)));startGPS();WebSocketService.connect();WebSocketService.joinRideRoom(a.id);setMessage('Corrida aceita. Navegação até o passageiro ativa.')}catch(e){const a=await active();if(a)setMessage('Corrida aceita com sucesso.');else setMessage(errText(e,'Não foi possível aceitar a corrida.'))}finally{setBusy(false)}}
 async function status(next){if(!ride||busy)return;setBusy(true);try{const u=(await axios.patch(BACKEND_URL+'/api/rides/'+ride.id+'/status',{status:next},{headers,timeout:12000})).data?.ride||{...ride,status:next};if(next==='IN_PROGRESS'){setRide(u);WebSocketService.startRide(ride.id,uid);setMessage('Corrida iniciada. Siga a rota até o destino.')}else if(next==='COMPLETED'){finish(u);WebSocketService.endRide(ride.id,uid)}}catch(e){setMessage(errText(e,'Não foi possível atualizar a corrida.'))}finally{setBusy(false)}}
 async function cancel(){if(!ride||busy||!window.confirm('Cancelar esta corrida?'))return;setBusy(true);try{await axios.patch(BACKEND_URL+'/api/rides/'+ride.id+'/status',{status:'CANCELLED',cancellationReason:'Cancelada pelo motorista'},{headers});WebSocketService.cancelRide(ride.id);clearRide('Corrida cancelada.')}catch(e){setMessage(errText(e,'Erro ao cancelar a corrida.'))}finally{setBusy(false)}}
 const pd=dist(driverLocation,passengerLocation),dd=dist(driverLocation,destinationAt(ride)),nearP=pd<=ARRIVAL_RADIUS_KM,nearD=dd<=ARRIVAL_RADIUS_KM;
 if(!user||user.userType!=='driver')return <div style={{padding:30}}>Acesso restrito ao motorista.</div>;
 return <div className="driver-pro"><style>{`.driver-pro{min-height:100vh;background:#f3f4f6;padding:18px;font-family:Arial}.driver-box{max-width:920px;margin:0 auto 15px;background:#fff;border-radius:18px;padding:18px;box-shadow:0 4px 18px rgba(0,0,0,.08)}.driver-row{display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}.driver-btn{border:0;border-radius:12px;padding:12px 16px;font-weight:800;cursor:pointer}.driver-btn:disabled{opacity:.5;cursor:not-allowed}.driver-on{background:#16a34a;color:#fff}.driver-off,.driver-danger{background:#dc2626;color:#fff}.driver-accent{background:#ff6a00;color:#fff}.driver-muted{color:#69717b;font-size:13px}.driver-avatar{width:52px;height:52px;border-radius:50%;background:#111;color:#fff;display:flex;align-items:center;justify-content:center;overflow:hidden;font-weight:800}.driver-avatar img{width:100%;height:100%;object-fit:cover}.driver-person{display:flex;gap:10px;align-items:center}.driver-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.driver-info{background:#f5f6f7;border-radius:12px;padding:11px}.driver-info b{display:block;color:#6b7280;font-size:12px;margin-bottom:4px}.driver-request{border:1px solid #e1e5e9;border-radius:15px;padding:14px;margin-top:10px}.driver-arrival{margin-top:12px;border-radius:14px;padding:12px;background:#fff7ed;border:1px solid #fed7aa}.driver-success{background:#ecfdf5;border:1px solid #a7f3d0;border-radius:16px;padding:16px}.driver-map-wrap{margin-top:12px}@media(max-width:640px){.driver-pro{padding:10px}.driver-grid{grid-template-columns:1fr}.driver-btn{width:100%}}`}</style>
 <div className="driver-box"><div className="driver-row"><div><h1 style={{margin:0}}>Painel do motorista</h1><div className="driver-muted">{user.name||user.email}</div></div><button className={'driver-btn '+(online?'driver-off':'driver-on')} disabled={busy||!!ride} onClick={toggle}>{busy?'Aguarde…':online?'Ficar offline':'Ficar online'}</button></div><p><b>Status:</b> {online?'🟢 Online':'⚪ Offline'}</p>{message&&<div className="driver-info">{message}</div>}</div>
 {completed&&<div className="driver-box"><div className="driver-success"><h2 style={{marginTop:0}}>✅ Corrida finalizada</h2><div className="driver-grid"><div className="driver-info"><b>Passageiro</b>{completed.passengerName}</div><div className="driver-info"><b>Valor da corrida</b>R$ {completed.price.toFixed(2)}</div><div className="driver-info"><b>Distância</b>{completed.distance.toFixed(2)} km</div><div className="driver-info"><b>Status</b>Concluída</div></div><p className="driver-muted">Voltando automaticamente ao painel inicial…</p></div></div>}
 {ride&&<div className="driver-box"><div className="driver-row"><h2 style={{margin:0}}>📍 Corrida atual</h2><b>{ride.status==='ACCEPTED'?'A CAMINHO DO PASSAGEIRO':'EM CORRIDA'}</b></div><div className="driver-person" style={{marginTop:12}}><Avatar photo={ride.passengerProfilePhoto} name={ride.passengerName}/><div><b>{ride.passengerName||'Passageiro'}</b><div className="driver-muted">{ride.status==='ACCEPTED'?'Vá até o embarque.':'Passageiro embarcado.'}</div></div></div><div className="driver-grid" style={{marginTop:12}}><div className="driver-info"><b>Embarque</b>{ride.origin?.address||'—'}{Number.isFinite(pd)&&<div className="driver-muted">{pd.toFixed(2)} km</div>}</div><div className="driver-info"><b>Destino</b>{ride.destination?.address||'—'}{ride.status==='IN_PROGRESS'&&Number.isFinite(dd)&&<div className="driver-muted">{dd.toFixed(2)} km</div>}</div><div className="driver-info"><b>Valor</b>R$ {Number(ride.price||0).toFixed(2)}</div><div className="driver-info"><b>Distância</b>{Number(ride.distance||0).toFixed(2)} km</div></div><DriverRideMap driverLocation={driverLocation} passengerLocation={passengerLocation} destinationLocation={destinationAt(ride)} status={ride.status}/>{ride.status==='ACCEPTED'&&<div className="driver-arrival"><b>{nearP?'✅ Você chegou ao passageiro.':'🚘 A caminho do passageiro.'}</b><div className="driver-muted">{nearP?'Após o embarque, inicie a corrida.':'O início é liberado ao chegar ao embarque.'}</div></div>}{ride.status==='IN_PROGRESS'&&<div className="driver-arrival"><b>{nearD?'✅ Você chegou ao destino.':'🧭 Rota até o destino ativa.'}</b><div className="driver-muted">{nearD?'Agora a corrida pode ser finalizada.':'Finalize somente ao chegar ao destino.'}</div></div>}<div className="driver-row" style={{marginTop:14}}>{ride.status==='ACCEPTED'&&<button className="driver-btn driver-accent" disabled={busy||!nearP} onClick={()=>status('IN_PROGRESS')}>{nearP?'👤 Passageiro embarcou • Iniciar':'📍 Aguardando chegada ao passageiro'}</button>}{ride.status==='IN_PROGRESS'&&<button className="driver-btn driver-on" disabled={busy||!nearD} onClick={()=>status('COMPLETED')}>{nearD?'✅ Finalizar no destino':'🧭 Vá até o destino para finalizar'}</button>}<button className="driver-btn driver-danger" disabled={busy} onClick={cancel}>Cancelar corrida</button></div></div>}
 {!ride&&<div className="driver-box"><h2>🔔 Solicitações</h2>{!online&&<p className="driver-muted">Fique online para receber corridas.</p>}{online&&requests.length===0&&<p className="driver-muted">Aguardando a próxima corrida mais próxima…</p>}{online&&requests.map(r=><div className="driver-request" key={r.id}><div className="driver-person"><Avatar photo={r.passengerProfilePhoto} name={r.passengerName}/><div><b>{r.passengerName||'Passageiro'}</b><div className="driver-muted">{r.estimatedDistanceKm!=null?r.estimatedDistanceKm+' km até o embarque':'Perto de você'}</div></div></div><p>📍 {r.origin?.address||'Embarque informado'}</p><p>🏁 {r.destination?.address||'Destino informado'}</p><p><b>R$ {Number(r.price||0).toFixed(2)}</b> • {Number(r.distance||0).toFixed(1)} km</p><button className="driver-btn driver-on" disabled={busy} onClick={()=>accept(r)}>{busy?'Aceitando…':'Aceitar corrida'}</button></div>)}</div>}
 </div>;
}
