import React,{useEffect,useMemo,useState}from'react';
import { BACKEND_URL as B } from '../config';

const css=`.pf-history{min-height:100vh;background:#030608;color:#f7f9fb;font-family:Arial,sans-serif;padding:18px 14px 100px}.pf-wrap{max-width:680px;margin:auto}.pf-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:8px 2px 18px}.pf-kicker{font-size:11px;font-weight:900;letter-spacing:.16em;color:#ff6b00;text-transform:uppercase}.pf-title{margin:4px 0 0;font-size:27px;font-weight:900;letter-spacing:-.04em}.pf-back{border:1px solid #28333b;background:#0b1115;color:#fff;border-radius:12px;padding:10px 13px;font-weight:800}.pf-summary{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-bottom:14px}.pf-stat{background:#070b0e;border:1px solid #28333b;border-radius:16px;padding:14px}.pf-stat strong{display:block;font-size:20px}.pf-stat span{display:block;margin-top:4px;color:#9ba7b1;font-size:12px}.pf-tabs{display:flex;gap:8px;overflow:auto;margin:4px 0 14px;padding-bottom:2px}.pf-tab{white-space:nowrap;border:1px solid #28333b;background:#0b1115;color:#9ba7b1;border-radius:999px;padding:9px 14px;font-weight:800}.pf-tab.active{background:#ff6b00;border-color:#ff6b00;color:#fff}.pf-list{display:flex;flex-direction:column;gap:10px}.pf-ride{background:#0b1115;border:1px solid #28333b;border-radius:18px;padding:15px;box-shadow:0 12px 28px rgba(0,0,0,.22)}.pf-ride-top{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.pf-status{font-size:11px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;color:#ff8a1d}.pf-price{font-size:20px;font-weight:900;color:#fff}.pf-route{margin:14px 0 12px;position:relative;padding-left:25px}.pf-route:before{content:'';position:absolute;left:7px;top:8px;bottom:8px;border-left:2px dashed #28333b}.pf-point{position:relative;margin:9px 0;color:#f7f9fb;font-size:14px;line-height:1.35}.pf-point:before{content:'';position:absolute;left:-22px;top:4px;width:9px;height:9px;border-radius:50%;background:#ff6b00;box-shadow:0 0 0 3px rgba(255,107,0,.12)}.pf-point.dest:before{background:#ffc400}.pf-meta{display:flex;justify-content:space-between;gap:8px;flex-wrap:wrap;color:#9ba7b1;font-size:12px;border-top:1px solid #28333b;padding-top:11px}.pf-person{margin-top:10px;color:#d8dee3;font-size:13px}.pf-empty{background:#0b1115;border:1px dashed #28333b;border-radius:18px;padding:28px 18px;text-align:center;color:#9ba7b1}.pf-more{width:100%;margin-top:12px;border:1px solid #28333b;background:#070b0e;color:#fff;border-radius:13px;padding:12px;font-weight:800}@media(max-width:420px){.pf-title{font-size:24px}.pf-summary{grid-template-columns:repeat(2,1fr)}.pf-stat{padding:12px}.pf-stat strong{font-size:18px}}`;

export default function RideHistoryPro({user,onBack}){
 const[rides,setRides]=useState([]),[loading,setLoading]=useState(true),[filter,setFilter]=useState('ALL'),[limit,setLimit]=useState(50);
 const load=()=>{const t=localStorage.getItem('token');if(!t){setLoading(false);return}setLoading(true);fetch(`${B}/api/rides/history?limit=${limit}`,{headers:{Authorization:`Bearer ${t}`},cache:'no-store'}).then(r=>{if(!r.ok)throw Error('history');return r.json()}).then(d=>setRides(Array.isArray(d.rides)?d.rides:[])).catch(()=>{}).finally(()=>setLoading(false))};
 useEffect(()=>{load();const i=setInterval(load,10000);const f=()=>load();window.addEventListener('focus',f);return()=>{clearInterval(i);window.removeEventListener('focus',f)}},[limit]);
 const done=rides.filter(r=>['COMPLETED','completed','CONCLUIDA','concluida'].includes(r.status));
 const cancelled=rides.filter(r=>['CANCELLED','cancelled','CANCELED','canceled','CANCELADA','cancelada'].includes(r.status));
 const visible=useMemo(()=>filter==='DONE'?done:filter==='CANCELLED'?cancelled:rides,[filter,rides]);
 const spent=done.reduce((s,r)=>s+Number(r.price||17),0),distance=done.reduce((s,r)=>s+Number(r.distance||0),0);
 const label=s=>{if(['COMPLETED','completed','CONCLUIDA','concluida'].includes(s))return'Concluída';if(['CANCELLED','cancelled','CANCELED','canceled','CANCELADA','cancelada'].includes(s))return'Cancelada';if(['ACCEPTED','accepted'].includes(s))return'Aceita';if(['IN_PROGRESS','in_progress'].includes(s))return'Em andamento';return s||'Corrida'};
 return <div className="pf-history"><style>{css}</style><div className="pf-wrap">
  <header className="pf-head"><div><div className="pf-kicker">PREÇO FIXO 17 • CORRIDAS</div><h1 className="pf-title">Minhas corridas</h1></div><button className="pf-back" onClick={onBack}>Voltar</button></header>
  <section className="pf-summary"><div className="pf-stat"><strong>{rides.length}</strong><span>Total de corridas</span></div><div className="pf-stat"><strong>{done.length}</strong><span>Concluídas</span></div><div className="pf-stat"><strong>R$ {spent.toFixed(2).replace('.',',')}</strong><span>Valor concluído</span></div><div className="pf-stat"><strong>{distance.toFixed(1).replace('.',',')} km</strong><span>Distância</span></div></section>
  <nav className="pf-tabs" aria-label="Filtro de corridas"><button className={'pf-tab '+(filter==='ALL'?'active':'')} onClick={()=>setFilter('ALL')}>Todas</button><button className={'pf-tab '+(filter==='DONE'?'active':'')} onClick={()=>setFilter('DONE')}>Concluídas</button><button className={'pf-tab '+(filter==='CANCELLED'?'active':'')} onClick={()=>setFilter('CANCELLED')}>Canceladas</button></nav>
  <main className="pf-list">{loading&&!rides.length?<div className="pf-empty">Carregando suas corridas…</div>:!visible.length?<div className="pf-empty">Nenhuma corrida nesta categoria.</div>:visible.map(r=><article className="pf-ride" key={r.id}><div className="pf-ride-top"><div><div className="pf-status">{label(r.status)}</div><div className="pf-person">{user?.userType==='driver'&&r.passengerName?`Passageiro: ${r.passengerName}`:r.driverName?`Motorista: ${r.driverName}`:'Corrida particular'}</div></div><div className="pf-price">R$ {Number(r.price||17).toFixed(2).replace('.',',')}</div></div><div className="pf-route"><div className="pf-point">{r.origin?.address||r.origin?.formattedAddress||'Origem não informada'}</div><div className="pf-point dest">{r.destination?.address||r.destination?.formattedAddress||'Destino não informado'}</div></div><div className="pf-meta"><span>{Number(r.distance||0).toFixed(1).replace('.',',')} km</span><span>{r.createdAt?new Date(Number(r.createdAt)).toLocaleString('pt-BR'):'Data não informada'}</span></div></article>)}</main>
  {rides.length>=limit&&<button className="pf-more" onClick={()=>setLimit(v=>v+50)}>Ver mais corridas</button>}
 </div></div>;
}